export interface IFakeData {
  id: string;
  averageScore: number;
  name: string;
  description: string;
  genres: string[];
  releaseYear: number;
  company: string[];
  esrbRating: string;
  averageTimeToBeat: number;
  thumbUrl: string;
  platform: string[];
  MainHover?: boolean;
}

export const FakeData: IFakeData[] = [
  {
    id: '1',
    averageScore: 87,
    name: 'Mario Kart: Double Dash',
    description:
      'Join Mario and his friends as they race karts on a variety of tracks, using power-ups to gain an advantage in this thrilling racing game. Team up with a partner to combine special abilities and secure victory in chaotic races filled with excitement and competition.',
    genres: ['Racing'],
    releaseYear: 2003,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 8.5,
    thumbUrl: 'DoubleDash',
    platform: ['GameCube'],
  },
  {
    id: '2',
    averageScore: 97,
    name: 'Metroid Prime',
    description:
      'Embark on a first-person action-adventure in Metroid Prime, where you step into the armored suit of Samus Aran. Explore the mysterious planet Tallon IV, uncover ancient secrets, battle hostile alien species, and upgrade your abilities in a visually stunning, immersive 3D world filled with danger and discovery.',
    genres: ['MetroidVania', 'Action-adventure', 'Sci-fi'],
    releaseYear: 2002,
    company: ['Retro Studios', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 13,
    thumbUrl: 'MetroidPrime',
    platform: ['GameCube', 'Wii'],
  },
  {
    id: '3',
    averageScore: 97,
    name: "Tony Hawk's Pro Skater 3",
    description:
      "Grab your skateboard and get ready for adrenaline-pumping action in Tony Hawk's Pro Skater 3. Perform gravity-defying tricks, complete objectives in diverse skateparks, and experience the thrill of skateboarding at its finest in this iconic sports game.",
    genres: ['Sports'],
    releaseYear: 2002,
    company: ['Neversoft', 'Activision'],
    esrbRating: 'T',
    averageTimeToBeat: 9,
    platform: ['GameCube', 'N64', 'PS1', 'PS2', 'XBOX', 'GBC', 'GBA', 'PC'],
    thumbUrl: 'THPS3',
  },
  {
    id: '4',
    averageScore: 96,
    name: 'Resident Evil 4',
    description:
      "Follow Leon S. Kennedy on a mission to rescue the President's daughter from a remote village infested with terrifying creatures. In Resident Evil 4, survival is paramount as you navigate a world of horror, uncovering dark secrets and facing relentless enemies in a gripping third-person shooter.",
    genres: ['Survival horror', 'Third-person shooter'],
    releaseYear: 2005,
    company: ['Capcom'],
    esrbRating: 'M',
    averageTimeToBeat: 15.5,
    thumbUrl: 'RE4',
    platform: [
      'GameCube',
      'Wii',
      'Switch',
      'PS2',
      'PS3',
      'PS4',
      'PC',
      'XBOX 360',
      'XBOX One',
      'XBOX Series',
      'Android',
      'IOS',
      /*Freking*/ 'Zeebo',
    ],
  },
  {
    id: '5',
    averageScore: 90,
    name: 'Pikmin 2',
    description:
      'Return to the charming world of Pikmin in this real-time strategy adventure. Join Captain Olimar and Louie on a quest to recover valuable treasures and save their company. Command armies of adorable Pikmin creatures, each with unique abilities, to solve puzzles and conquer challenges.',
    genres: ['Real Time Strategy'],
    releaseYear: 2001,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 11.5,
    thumbUrl: 'Pikmin2',
    platform: ['GameCube', 'Wii'],
  },
  {
    id: '6',
    averageScore: 73,
    name: 'Sonic Adventure 2 Battle',
    description:
      "Join Sonic and his friends in a high-speed action-adventure as they race against the evil Dr. Eggman to save the world. Sonic Adventure 2 Battle combines thrilling action, platforming, and the power of teamwork as you work to thwart Dr. Eggman's plans.",
    genres: ['Action', 'Adventure'],
    releaseYear: 2002,
    company: ['Sonic Team', 'Sega'],
    esrbRating: 'E',
    averageTimeToBeat: 9,
    thumbUrl: 'SA2Battle',
    platform: ['GameCube', 'PC', 'PS3', 'XBOX 360'],
  },
  {
    id: '7',
    averageScore: 87,
    name: 'Animal Crossing',
    description:
      'Escape to a delightful life simulation in Animal Crossing, where you move to a peaceful village inhabited by charming anthropomorphic animal neighbors. Customize your home, participate in seasonal events, and enjoy the simple pleasures of daily life in this heartwarming and relaxing game.',
    genres: ['Life Simulation'],
    releaseYear: 2001,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 68,
    thumbUrl: 'AnimalCrossing',
    platform: ['GameCube', 'N64'],
  },
  {
    id: '8',
    averageScore: 61,
    name: 'Kirby Air Ride',
    description:
      "Take control of Kirby and his friends in a high-speed, colorful racing game. Zoom through imaginative courses, utilize Kirby's unique abilities, and compete against friends in multiplayer races filled with excitement and surprises.",
    genres: ['Racing'],
    releaseYear: 2003,
    company: ['HAL Laboratory', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 2,
    thumbUrl: 'AirRide',
    platform: ['GameCube'],
  },
  {
    id: '9',
    averageScore: 87,
    name: 'Paper Mario: The Thousand-Year Door',
    description:
      'Embark on a whimsical and humorous journey with Mario in Paper Mario: The Thousand-Year Door. Help Mario rescue Princess Peach from the clutches of the evil X-Nauts, solve clever puzzles, and engage in turn-based battles filled with charm and strategy.',
    genres: ['Role-Playing', 'Adventure'],
    releaseYear: 2004,
    company: ['Intelligent Systems', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 30,
    thumbUrl: 'PaperMario',
    platform: ['GameCube'],
  },
  {
    id: '10',
    averageScore: 96,
    name: 'The Legend of Zelda: The Wind Waker',
    description:
      'Set sail on a grand seafaring adventure as Link in The Legend of Zelda: The Wind Waker. Explore a vast and beautiful world, solve intricate puzzles, and battle menacing foes to rescue your sister and thwart the plans of the malevolent sorcerer Ganon.',
    genres: ['Action-adventure', 'Exploration', 'Puzzle-solving', 'Action RPG'],
    releaseYear: 2002,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 29,
    thumbUrl: 'WindWaker',
    platform: ['GameCube'],
  },
  {
    id: '11',
    averageScore: 96,
    name: 'The Legend of Zelda: Twilight Princess',
    description:
      'Embark on an epic action-adventure in The Legend of Zelda: Twilight Princess. Assume the role of Link as you set out to save Hyrule from an impending darkness. Solve puzzles, wield the legendary Master Sword, and form a unique partnership with the enigmatic Midna in a tale of courage and destiny.',
    genres: ['Action-adventure', 'Exploration', 'Puzzle-solving', 'Action RPG'],
    releaseYear: 2006,
    company: ['Nintendo'],
    esrbRating: 'T',
    averageTimeToBeat: 37,
    platform: ['GameCube', 'Wii'],
    thumbUrl: 'TwilightPrincess',
  },
  {
    id: '12',
    averageScore: 92,
    name: 'Super Smash Bros. Melee',
    description:
      "Engage in multiplayer mayhem with a roster of beloved Nintendo characters in Super Smash Bros. Melee. Battle it out in iconic locations from Nintendo's universe, unleash powerful special moves, and experience fast-paced and competitive fighting gameplay.",
    genres: ['Fighting', 'Party'],
    releaseYear: 2001,
    company: ['HAL Laboratory', 'Nintendo'],
    esrbRating: 'T',
    averageTimeToBeat: 10,
    thumbUrl: 'Melee',
    platform: ['GameCube'],
  },
  {
    id: '13',
    averageScore: 89,
    name: 'Pikmin',
    description:
      'Enter the miniature world of Pikmin and join Captain Olimar in a real-time strategy adventure. Command and coordinate a colorful army of Pikmin creatures with distinct abilities to overcome obstacles, solve environmental puzzles, and recover your spaceship parts on an alien planet.',
    genres: ['Real Time Strategy'],
    releaseYear: 2001,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 8,
    platform: ['GameCube', 'Wii'],
    thumbUrl: 'Pikmin',
  },
  {
    id: '14',
    averageScore: 92,
    name: "Eternal Darkness: Sanity's Requiem",
    description:
      "Immerse yourself in a chilling survival horror adventure in Eternal Darkness: Sanity's Requiem. Play as multiple characters throughout history and uncover the unsettling truths hidden within a mysterious tome known as the Necronomicon. Beware the effects of the sanity system as it plays tricks on your mind.",
    genres: ['Survival horror', 'Action-adventure'],
    releaseYear: 2002,
    company: ['Silicon Knights', 'Nintendo'],
    esrbRating: 'M',
    averageTimeToBeat: 13,
    thumbUrl: 'EternalDarkness',
    platform: ['GameCube'],
  },
  {
    id: '15',
    averageScore: 89,
    name: 'F-Zero GX',
    description:
      'Prepare for high-speed thrills in F-Zero GX, a futuristic racing game featuring an array of cutting-edge vehicles and intense tracks. Race against skilled opponents in a visually stunning and fast-paced competition where split-second decisions determine victory.',
    genres: ['Racing'],
    releaseYear: 2003,
    company: ['Amusement Vision', 'Sega', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 9,
    platform: ['GameCube'],
    thumbUrl: 'FZeroGX',
  },
  {
    id: '16',
    averageScore: 85,
    name: 'Metal Gear Solid: The Twin Snakes',
    description:
      'Experience a reimagining of the original Metal Gear Solid in Metal Gear Solid: The Twin Snakes. This enhanced version features improved graphics and gameplay mechanics as you follow the iconic Solid Snake on a mission filled with espionage, action, and intrigue.',
    genres: ['Action', 'Stealth'],
    releaseYear: 2004,
    company: ['Silicon Knights', 'Konami'],
    esrbRating: 'M',
    averageTimeToBeat: 10,
    platform: ['GameCube'],
    thumbUrl: 'MGS1',
  },
  {
    id: '17',
    averageScore: 91,
    name: 'Resident Evil',
    description:
      'Return to the mansion of horror in Resident Evil, a gripping survival horror game and a remake of the original. Navigate its treacherous halls, solve puzzles, and face gruesome creatures as you uncover the secrets behind the eerie Spencer Mansion.',
    genres: ['Survival Horror'],
    releaseYear: 2002,
    company: ['Capcom'],
    esrbRating: 'M',
    averageTimeToBeat: 11,
    platform: ['GameCube', 'PC', 'PS3', 'PS4', 'XBOX 360', 'ONE'],
    thumbUrl: 'RE',
  },
  {
    id: '18',
    averageScore: 85,
    name: 'Ikaruga',
    description:
      'Enter the intense world of Ikaruga, a vertically scrolling shooter known for its unique polarity-switching mechanic. Switch between two polarities to absorb or deflect enemy bullets while navigating challenging levels filled with relentless foes.',
    genres: ['Shooter'],
    releaseYear: 2003,
    company: ['Treasure'],
    esrbRating: 'E',
    averageTimeToBeat: 1.5,
    platform: ['GameCube', 'Arcade', 'Dreamcast', 'XBOX 360', 'Switch'],
    thumbUrl: 'Ikaruga',
  },
  {
    id: '19',
    averageScore: 78,
    name: "Luigi's Mansion",
    description:
      "Join Luigi on a ghostly adventure in Luigi's Mansion. Armed with a vacuum cleaner, he must navigate a haunted mansion to rescue his brother Mario from mischievous and misbehaving spirits. Explore spooky rooms, solve puzzles, and capture ghosts in this charming action-adventure.",
    genres: ['Action', 'Adventure'],
    releaseYear: 2001,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 6.5,
    platform: ['GameCube'],
    thumbUrl: 'LuigiMansion',
  },
  {
    id: '20',
    averageScore: 89,
    name: 'Phantasy Star Online Episode I & II',
    description:
      'Embark on an online multiplayer action RPG adventure in Phantasy Star Online Episode I & II. Set in a futuristic and expansive sci-fi universe, team up with players from around the world to explore various worlds, battle formidable enemies, and discover the mysteries of the Phantasy Star universe.',
    genres: ['Action', 'RPG'],
    releaseYear: 2002,
    company: ['Sonic Team', 'Sega'],
    esrbRating: 'T',
    averageTimeToBeat: 54,
    platform: ['GameCube', 'XBOX', 'Dreamcast', 'PC'],
    thumbUrl: 'PhantasyStar',
  },
  {
    id: '21',
    averageScore: 75,
    name: 'Chibi-Robo!',
    description:
      'Step into the shoes of Chibi-Robo, a tiny robot on a big adventure. In this heartwarming and quirky adventure game, help Chibi-Robo assist a family with their household chores, solve mysteries, and uncover the secrets hidden within their home.',
    genres: ['Adventure'],
    releaseYear: 2005,
    company: ['Skip Ltd.', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 12,
    platform: ['GameCube'],
    thumbUrl: 'ChibiRobo',
  },
  {
    id: '22',
    averageScore: 45,
    name: 'Shadow the Hedgehog',
    description:
      "Join Sonic's enigmatic rival, Shadow the Hedgehog, in a dark and action-packed adventure. Uncover the mysteries of Shadow's past as you navigate through a world filled with choices, alliances, and consequences, all while battling fierce enemies.",
    genres: ['Action', 'Adventure'],
    releaseYear: 2005,
    company: ['Sonic Team', 'Sega'],
    esrbRating: 'E10+',
    averageTimeToBeat: 4.5,
    platform: ['GameCube', 'PS2', 'XBOX'],
    thumbUrl: 'Shadow',
  },
  {
    id: '23',
    averageScore: 93,
    name: 'SoulCalibur II',
    description:
      'Enter the arena and engage in epic weapon-based battles in SoulCalibur II. Featuring a diverse roster of characters, each with their own unique fighting style, this fighting game offers fast-paced combat and challenging duels in beautifully designed arenas.',
    genres: ['Fighting'],
    releaseYear: 2003,
    company: ['Project Soul', 'Namco'],
    esrbRating: 'T',
    averageTimeToBeat: 3.5,
    platform: ['GameCube', 'PS2', 'XBOX'],
    thumbUrl: 'SoulCalibur2',
  },
  {
    id: '24',
    averageScore: 90,
    name: 'Star Wars: Rogue Leader - Rogue Squadron II',
    description:
      'Take to the skies in Star Wars: Rogue Leader - Rogue Squadron II, a thrilling flight combat game set in the iconic Star Wars universe. Assume the role of Rebel pilots in daring missions against the Galactic Empire, and relive epic battles from the Star Wars films.',
    genres: ['Flight Combat'],
    releaseYear: 2001,
    company: ['Factor 5', 'LucasArts'],
    esrbRating: 'T',
    averageTimeToBeat: 6.5,
    platform: ['GameCube'],
    thumbUrl: 'StarWarsRougeLeader',
  },
  {
    id: '25',
    averageScore: 76,
    name: 'Super Mario Strikers',
    description:
      'Experience soccer with a Mario twist in Super Mario Strikers. Join Mario and his friends on the soccer field for a fast-paced and competitive arcade-style soccer game. Use special moves, power-ups, and teamwork to outscore your opponents and claim victory.',
    genres: ['Sports', 'Football'],
    releaseYear: 2005,
    company: ['Next Level Games', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 6,
    platform: ['GameCube'],
    thumbUrl: 'Strikers',
  },
  {
    id: '26',
    averageScore: 73,
    name: 'Pokémon Colosseum',
    description:
      'Experience the world of Pokémon in a new light with Pokémon Colosseum. Set in the unique Orre region, embark on a quest to rescue Shadow Pokémon from their darkness and thwart the nefarious plans of the Cipher group. Engage in thrilling 3D battles and explore a different side of the Pokémon universe.',
    genres: ['Role-Playing'],
    releaseYear: 2005,
    company: ['Game Freak', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 24,
    thumbUrl: 'PokemonColosseum',
    platform: ['GameCube'],
  },
  {
    id: '27',
    averageScore: 82,
    name: 'Tomb Raider: Legend',
    description:
      'Join Lara Croft in Tomb Raider: Legend as she embarks on a globe-trotting adventure to uncover the mysteries of ancient artifacts. Traverse exotic locations, solve challenging puzzles, and engage in intense action sequences in this action-adventure game.',
    genres: ['Action', 'Adventure'],
    releaseYear: 2006,
    company: ['Crystal Dynamics', 'Eidos Interactive'],
    esrbRating: 'T',
    averageTimeToBeat: 7,
    platform: ['GameCube', 'GBA', 'DS', 'PC', 'PS2', 'PSP', 'XBOX', 'XBOX 360'],
    thumbUrl: 'TombRaiderLegend',
  },
  {
    id: '28',
    averageScore: 59,
    name: 'Crazy Taxi',
    description:
      'Take on the role of a fearless taxi driver in Crazy Taxi, an arcade-style racing game where speed and precision are paramount. Race against the clock to pick up and drop off passengers in a vibrant city filled with wild shortcuts and traffic chaos.',
    genres: ['Racing'],
    releaseYear: 2001,
    company: ['Hitmaker', 'Sega'],
    esrbRating: 'T',
    averageTimeToBeat: 3,
    platform: ['GameCube', 'PS2', 'XBOX', 'DreamCast'],
    thumbUrl: 'CrazyTaxi',
  },
  {
    id: '29',
    averageScore: 73,
    name: 'BloodRayne',
    description:
      "Assume the role of Rayne, a dhampir with extraordinary abilities, in BloodRayne. Venture into a world of supernatural threats as you battle grotesque enemies and uncover a dark and mysterious plot. Engage in action-packed combat and harness Rayne's unique powers.",
    genres: ['Action', 'Adventure'],
    releaseYear: 2002,
    company: ['Terminal Reality', 'Majesco Entertainment'],
    esrbRating: 'M',
    averageTimeToBeat: 7,
    platform: ['GameCube', 'PS2', 'XBOX', 'PC'],
    thumbUrl: 'BloodRayne',
  },
  {
    id: '30',
    averageScore: 87,
    name: 'Beyond Good & Evil',
    description:
      'Embark on a captivating action-adventure in Beyond Good & Evil. Play as Jade, a photojournalist, as she investigates a conspiracy on a distant planet. Uncover the truth, capture compelling photographs, and engage in thrilling action sequences in a beautifully crafted world.',
    genres: ['Action', 'Adventure'],
    releaseYear: 2003,
    company: ['Ubisoft Montpellier', 'Ubisoft'],
    esrbRating: 'T',
    averageTimeToBeat: 11,
    platform: ['GameCube', 'PS2', 'PS3', 'XBOX', 'XBOX 360', 'PC'],
    thumbUrl: 'Beyond',
  },
];
