export const FakeData = [
  {
    name: 'The Legend of Zelda: The Wind Waker',
    description:
      'Link sets out on a seafaring adventure to rescue his sister and save the world from the evil sorcerer Ganon.',
    genres: ['Action-adventure', 'Exploration', 'Puzzle-solving'],
    releaseYear: 2002,
    company: ['Nintendo EAD', 'Capcom'],
    esrbRating: 'E',
    averageTimeToBeat: 28,
    platform: ['Gamecube'],
  },
  {
    name: 'Metroid Fusion',
    description:
      'Samus Aran must stop a dangerous alien parasite from taking over her body and wreaking havoc on the galaxy.',
    genres: ['Action-adventure', 'Platformer', 'Sci-fi'],
    releaseYear: 2002,
    company: ['Nintendo R&D1'],
    esrbRating: 'E',
    averageTimeToBeat: 8,
    platform: ['GBA'],
  },
  {
    name: 'Super Smash Bros. Melee',
    description:
      'A multiplayer fighting game featuring a roster of Nintendo characters battling it out in iconic locations from their games.',
    genres: ['Fighting', 'Party'],
    releaseYear: 2001,
    company: ['HAL Laboratory'],
    esrbRating: 'T',
    averageTimeToBeat: 15,
    platform: ['Gamecube'],
  },
  {
    name: 'Mario & Luigi: Superstar Saga',
    description:
      'Join Mario and Luigi on an epic adventure to save the Beanbean Kingdom.',
    genres: ['Role-Playing', 'Adventure'],
    releaseYear: 2003,
    company: ['AlphaDream', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 20,
    platform: ['Game Boy Advance'],
  },
  {
    name: 'Paper Mario: The Thousand-Year Door',
    description:
      'Help Mario on his quest to save Princess Peach from the evil X-Nauts.',
    genres: ['Role-Playing', 'Adventure'],
    releaseYear: 2004,
    company: ['Intelligent Systems', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 30,
    platform: ['Gamecube'],
  },
  {
    name: 'Kirby & the Amazing Mirror',
    description:
      'Guide Kirby through a sprawling labyrinth to defeat Dark Meta Knight.',
    genres: ['Action', 'Adventure'],
    releaseYear: 2004,
    company: ['HAL Laboratory', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 8,
    platform: ['Game Boy Advance'],
  },
  {
    name: 'Animal Crossing',
    description:
      'Create your own virtual life in a charming town filled with friendly animals.',
    genres: ['Simulation'],
    releaseYear: 2001,
    company: ['Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 60,
    platform: ['Gamecube'],
  },
  {
    name: 'Golden Sun',
    description: 'Embark on a quest to prevent the release of an ancient evil.',
    genres: ['Role-Playing'],
    releaseYear: 2001,
    company: ['Camelot Software Planning', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 25,
    platform: ['Game Boy Advance'],
  },

  {
    name: 'Fire Emblem',
    description: 'Lead your army to victory in turn-based tactical battles.',
    genres: ['Strategy', 'Role-Playing'],
    releaseYear: 2003,
    company: ['Intelligent Systems', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 25,
    platform: ['Game Boy Advance'],
  },
  {
    name: 'Mario Party 7',
    description:
      'Compete with friends in a variety of fun and wacky minigames.',
    genres: ['Party', 'Board Game'],
    releaseYear: 2005,
    company: ['Hudson Soft', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 3,
    platform: ['Gamecube'],
  },
  {
    name: 'Pokémon Emerald',
    description: "Catch 'em all and become the Champion in the Hoenn region.",
    genres: ['Role-Playing'],
    releaseYear: 2005,
    company: ['Game Freak', 'Nintendo'],
    esrbRating: 'E',
    averageTimeToBeat: 25,
    platform: ['Game Boy Advance'],
  },
  {
    name: 'Metroid: Zero Mission',
    description:
      'Explore the planet Zebes and uncover the origins of Samus Aran.',
    genres: ['Action', 'Adventure'],
    releaseYear: 2004,
    company: ['Nintendo', 'Intelligent Systems'],
    esrbRating: 'E',
    averageTimeToBeat: 7,
    platform: ['Game Boy Advance'],
  },
];
